swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport:  '%env(MAILER_TRANSPORT)%'
            host:       '%env(MAILER_HOST)%'
            username:   '%env(MAILER_USER)%'
            password:   '%env(MAILER_PASSWORD)%'
            port:       '%env(MAILER_PORT)%'
            encryption: ssl
            auth_mode:  login
            spool: { type: 'memory' }