vich_uploader:
    db_driver: orm
    mappings:
        file:
            upload_destination: '%kernel.project_dir%/uploads'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid