POST {{host}}:{{port}}/recover_password_request
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
x-view-analytics: {{switchUser}}

{
  "email":"admin@admin.com"
}

###

POST {{host}}:{{port}}/reset_password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
x-view-analytics: {{switchUser}}

{
  "token":"D0AB8LwylhWFhavwFYzXS5VFWsL7QtzFc8TkMubb8hAZIUGLZCNrZ6bOROpbcnhULsXuYtNNG4huJgwHVschoS0UL4Zxe78iKYA9GY0WJByTBgYwNQ0Sd2kMorueLFL3pkOH3wip1LwmqnNmMmiJgnfYakmc625Kd2zo5Z3njHnZEGkAWOMIOAXMbooI0hCgWqPHIIe2",
  "password": "admin"
}

###


