monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [{ 404: ['^/(?!api)'] }, {405: ['^/(?!api)']} ]
        grouped:
            type: group
            members: [nested, deduplicated_slack]
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        deduplicated_slack:
            type: deduplication
            time: 120 #Seconds of deduplication
            handler: slackbot
        slackbot:
            type: slack
            token: '%env(SLACK_BOT_TOKEN)%'
            channel: '%env(SLACK_LOGS_CHANNEL)%'
            subject: 'Error de servidor'
            level: error
            bubble: false
            include_extra: true
            use_short_attachment: true