# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Store session data in database
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
        #- 'mysql:dbname=mydatabase'
        #- { db_username: myuser, db_password: mypassword }
        - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }


    'App\Filter\NotificationExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }


    # Fulltext search filter
    app.filter.search:
        class: App\Filter\SearchFilter
        arguments:
        - '@doctrine'
        - '@request_stack'
        - '@?logger'
        - null
        - '@doctrine.orm.entity_manager'
        tags: [{ name: api_platform.filter, id: search }]

    # Request info
    app.monolog.processor:
        class: App\Monolog\AppProcessor
        tags:
            - { name: monolog.processor }

    'App\Serializer\CustomSerializationGroups':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\CustomSerializationGroups.inner' ]
        autoconfigure: false

    aws_ses_client:
        class: Aws\Ses\SesClient
        arguments:
            - region: "%env(AWS_REGION)%"
              version: "2010-12-01"

    'App\Helpers\Mailer':
        class: App\Helpers\Mailer
        arguments:
            - "@aws_ses_client"
            
    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false

